import turtle
import math

wn = turtle.Screen()
wn.bgcolor("plum")
wn.title("Turtle6663629")
skk = turtle.Turtle()
skk.shape('circle')
skk.fillcolor('purple')
skk.speed(0)


# skk.penup()
# skk.left(45)
# skk.forward(100*math.sqrt(2))
# skk.pendown()
# skk.begin_fill()
# skk.left(135)
# skk.forward(200)
# skk.left(90)
# skk.forward(200)
# skk.left(90)
# skk.forward(200)
# skk.left(90)
# skk.forward(200)
# skk.end_fill()
#
# skk.penup()
# skk.right(45)
# skk.forward(100*math.sqrt(2))
# skk.pendown()
# skk.left(135)
# skk.forward(400)
# skk.left(90)
# skk.forward(400)
# skk.left(90)
# skk.forward(400)
# skk.left(90)
# skk.forward(400)
#
# skk.penup()
# skk.right(45)
# skk.forward(100*math.sqrt(2))
# skk.pendown()
# skk.left(135)
# skk.forward(600)
# skk.left(90)
# skk.forward(600)
# skk.left(90)
# skk.forward(600)
# skk.left(90)
# skk.forward(600)

skk.penup()
skk.goto(300,0)
skk.pendown()
skk.fillcolor('aquamarine')
skk.begin_fill()
skk.circle(300)
skk.end_fill()

skk.penup()
skk.goto(200,0)
skk.pendown()
skk.fillcolor('cyan')
skk.begin_fill()
skk.circle(200)
skk.end_fill()

skk.penup()
skk.goto(100,0)
skk.pendown()
skk.fillcolor('white smoke')
skk.begin_fill()
skk.circle(100)
skk.end_fill()


skk.penup()
skk.goto(0,0)
skk.fillcolor('lavender')
skk.setheading(90)

turtle.done()
